### ISSUE TITLE
Storage access is done for generating media url

### ISSUE THREAD

**Issue by alexander-schranz** [pawel-brzezinski/sulu-storage-bundle#2]
Its a huge performance issue when for every mediaUrl generation a file exist check is done here: https://github.com/pawel-brzezinski/sulu-storage-bundle/blob/e30be20762003f9726b345fc2373fc5fb0fccb66/FormatCache/PBFormatCache.php#L117

Not sure why it is needed but it should be avoided.

**Comment by spras** [comment]
FYI : i can be by-passed using `league/flysystem-cached-adapter`
https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Resources/doc/filesystem_cache.md

**Comment by pawel-brzezinski** [comment]
Hello, issue fixed in version 1.0. I agree that for better performance cache adapter should be configured.

Thanks.
