### ISSUE TITLE
ExternalUrlResolver with CachedAdapter return relative URL

### ISSUE THREAD

**Issue by spras** [pawel-brzezinski/sulu-storage-bundle#3]
AwsS3v3ExternalUrlResolver, when used with a CachedAdater, return null , then in PBFormatCache->getMediaUrl , it return the relative URL instead of external URL ! 

This lead to continuously ask the local URL of Sulu (uploads/media) !

**Comment by pawel-brzezinski** [comment]
Hi, 
Thanks for PR. I decided to rewrite bundle. In new version this issue has been solved.

Thanks for your activity :)
